<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <?php //echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
                                      ->prependFile('https://apis.google.com/js/plusone.js') 
                                      ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js') 
                                      ->prependFile('http://www.linats.net/led-projector/popup.js') 
                                      ->prependFile($this->basePath() . '/js/recherche.js') 
                                      ->prependFile($this->basePath() . '/js/script4.js')
                                      ->prependFile('http://www.linats.net/led-projector/popup.js') 
                                      ->prependFile('/js/cherchedanspage.js') 
                                      ->prependFile('http://www.david-argence.com/bradis-Tv9xE/pub_coin.js')
                                      ->prependFile('http://pagead2.googlesyndication.com/pagead/show_ads.js')
                                      ->prependFile('http://pagead2.googlesyndication.com/pagead/show_ads.js')                                 
                                      ?>

    </head>
    <body>
      <SCRIPT language="JavaScript">InitBulle("navy","#FFCC66","orange",1);
        // InitBulle(couleur de texte, couleur de fond, couleur de contour taille contour)
      </SCRIPT>
     <div id="principal" align=center><!-- /div principal -->
        <div>
       
            <table border=0" width="900">

      <tr>
        <td width="110" valign="bottom">
          <a href="home.php"><img src="img/img-lampe/lampe-videoprojecteur.info" border="0" alt="lampe videoprojecteur"></a>
        </td>
        <td valign="bottom">
        <h1 style="font-size:30px"><a href="lampe-videoprojecteur.php" title="Lampe videoprojecteur" >lampe-videoprojecteur</a><font color="#FF7F00">.info</font></h1><g:plusone></g:plusone><br/><br/>
        <img src="img/img-lampe/puce-orange.gif"><a href="">Tout savoir sur la lampe de videoprojecteur</a> (Accueil)
      <br><br>
      <img src="img/img-lampe/puce-grise.gif"><a href="videoprojecteur.php">Le videoprojecteur expliqu&eacute;</a>
      <br>
      <img src="img/img-lampe/puce-grise.gif"><a href="lampe.php">La lampe du videoprojecteur</a>
      <br>
      <img src="img/img-lampe/puce-clignotante.gif"><a href="lampe-videoprojecteur.php">Infos sur les lampes de videoprojecteurs par marques</a>
      <br>
      <img src="img/img-lampe/puce-grise.gif"><a href="http://www.homecinema-fr.com/forum/viewforum.php?f=84" target="_blank">Forum homecinema-fr.com</a>
      <br>
      <img src="img/img-lampe/puce-grise.gif"><a href="contact.php">Nous contacter</a><br>

      <style type="text/css">
      @import url(http://www.google.fr/cse/api/branding.css);
      </style>
      <div class="cse-branding-right" style="background-color:white;color:#000000">
        <div class="cse-branding-form">
          <form action="recherche.php" id="cse-search-box">
            <div>&nbsp;&nbsp;
              <input type="hidden" name="cx" value="partner-pub-9001598868705234:sxvj26o2zru" />
              <input type="hidden" name="cof" value="FORID:10" />
              <input type="hidden" name="ie" value="ISO-8859-1" />
              <input type="text" name="q" size="21" />
              <input type="submit" name="sa" value="Rechercher" />
            </div>
          </form>
        </div>
      </div>
      </td>


      <td align="right"><a href="infos-videoprojecteur.php"><img src="img/img-lampe/infos-videoprojecteur.gif" border="0" alt="Infos videoprojecteur"></a>
      </td>

      </tr>

      <tr><td colspan="3" bgcolor="#808080"></td></tr>


      <tr><td colspan="2">

        <font size="-2"><font color="#FF7F00">Partenaires</font>&nbsp;<a href="partenariat.php"><font color="#4ABDD6">Devenir partenaire</a></font><br></font>
         <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" 
        width="728" height="120" id="ad_loader" align="middle">
        <param name="allowScriptAccess" value="sameDomain"/>
        <param name="movie" value="xml/ad_loader.swf?xml_file=xml/ad_loader.xml"/>
        <param name="quality" value="high"/>
        <param name="bgcolor" value="#404040"/>
        <embed src="xml/ad_loader.swf?xml_file=xml/ad_loader.xml" quality="high" bgcolor="#404040" width="728" height="120" name="ad_loader" align="middle" 
        allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"/>
      </object>

        </td>
        <td>
        <table cellspacing="0" cellpadding="0"><tr><td>

          <a href="nouveautes-videoprojecteurs.php" title="Nouveaut&eacute;s projecteurs"><img src="img/img-lampe/vignette5-0.png" border="0" onmouseover=this.src="img/img-lampe/vignette5.png" onmouseout=this.src="img/img-lampe/vignette5-0.png"></a>
          </td><td>
          <a href="lampe-videoprojecteur.php" title="Infos Lampes et projecteurs"><img src="img/img-lampe/vignette1-0.png" border="0" onmouseover=this.src="img/img-lampe/vignette1.png" onmouseout=this.src="img/img-lampe/vignette1-0.png"></a>

          </td></tr>


          <!--
          <a href="service.php"><img src="img/img-lampe/vignette2-0.png" onmouseover=this.src="img/img-lampe/vignette2.png" border="0" onmouseout=this.src="img/img-lampe/vignette2-0.png"></a>
          -->

          <tr><td>
          <a href="annuaire-audiovisuel" title="Annuaire Audiovisuel"><img src="img/img-lampe/vignette4-0.png" border="0" onmouseover=this.src="img/img-lampe/vignette4.png" onmouseout=this.src="img/img-lampe/vignette4-0.png"></a>
          </td><td><a href="contact.php" title="Contact"><img src="img/img-lampe/vignette3-0.png" border="0" onmouseover=this.src="img/img-lampe/vignette3.png" onmouseout=this.src="img/img-lampe/vignette3-0.png"></a>
          </td></tr></table>
          </td>
              </tr>

        </table>
        </header>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
         </div>
    </body>
</html>
