<?php  
$this->layout()->title = 'Actualités Vidéoprojecteurs Achats en ligne';
$this->headMeta()
                ->appendName('keywords', "nouveautés vidéoprojecteurs")
                ->appendName('description', "Toutes les Nouveautés Vidéoprojecteurs Achats en ligne");
?>
<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.projopourtous.com" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="projopourtous" title="projopourtous" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->
<div class="ariane">
    <p>
        <a href="home"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>
        <span>&nbsp;&gt;&nbsp;<a href="nouveautes-videoprojecteurs.php" title="Nouveautés sur les lampes de vidéoprojecteurs par marques">Nouveautés sur les lampes de vidéoprojecteurs par marques</a></span><span>&nbsp;&gt;&nbsp;Achat en ligne</span>
    </p>
</div>
<!-- End Fil d'Ariane -->

<!-- Conteneur -->
<div class="containeur">
  <!-- Contenu -->
  <div class="contenu">
      <h2 class="titre_page">Actualit&eacute;s Vidéoprojecteurs & Lampes <?php echo $marque ?> 2011</h2>
      <p style="text-align:right;font-size:-1; color:#FF7F00">Votre actu ici ? <a href="contact.php" title="LampeVideoProjecteur Contactez-nous">Contactez-nous</a></p>
        <!-- D&eacute;but accordeon -->
      <div class="accordion acc" id="accordion2">
          <!-- -->
            <div class="accordion-group">

                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info1">25 ao&ucirc;t 2011</a>
                </div>
                <div id="info1" class="accordion-body collapse in">
                    <div class="accordion-inner">
                      <p>Vu sur Google.fr, en recherchant "lampe videoprojecteur":</p>
                        <img src="img/images/www.projectorlampsworld.fr.gif"></br></br>
                      <p>Toujours tr&egrave;s curieux, nous avons voulu tester ce nouveau venu. Voici...</br>   </br>
                        - pas de conditions g&eacute;n&eacute;rales de ventes (obligatoire en France, article L441-6 du code de commerce)</br>
                        - aucune indication sur la TVA et les droits de douanes &agrave; payer &agrave; la livraison. Surprise...</br>
                        - aucune indication sur la qualit&eacute; des lampes : lampes d'origine, lampes compatibles ? Myst&egrave;re...</br>
                        - aucune indication des d&eacute;lais de livraison. Myst&egrave;re...</br>
                        - aucune information formelle sur la garantie des lampes tant sur le descriptif produit qu'au moment de l'achat. Myst&egrave;re...</br>
                        - aucune information sur la disponibilit&eacute; des produits consult&eacute;s. Myst&egrave;re...</br>
                        - aucune adresse et aucun contact en France malgr&eacute; une extension .FR</br>
                        - en revanche, les prix sont ridiculement bas, jusqu'&agrave; 1/3 du prix constat&eacute; en France.</br>
                        - Affichage des logos <i>Paypal</i> et <i>Paypal Verified</i> alors que le paiement par Paypal n'est pas propos&eacute;.</br>
                        - <img src="img/images/danger.gif"> page de saisie du num&eacute;ro de carte bancaire <u>non-s&eacute;curis&eacute;e</u></br></br>
                        Pour avoir des r&eacute;ponses &agrave; nos interrogations, nous contactons le N&deg; de <i>"t&eacute;l&eacute;assistance"</i>, un num&eacute;ro &eacute;tranger mais on fait l'effort...</br>Personne n'est capable de nous r&eacute;pondre en fran&ccedil;ais (rappelons que ce site web est en .FR).</br></br>
                        Nous ne nous d&eacute;courageons pas pour autant et on envoyons un mail. La r&eacute;ponse ne tarde pas :</br></br>
                      </p>
                      <table class="table-lettre"><tr><td>
                      <span  style="font-weight:bold;">Dear Sir</span><br>
                      Please be notified that we are an English-speaking company and<br>
                      as much as we would like to assist you, we really could not<br>
                      understand the content of your email. If you could kindly translate it to<br>
                      English, we would be more than happy to accommodate<br>
                      your request.<br>
                      Thank you.<br>
                      <span>With best regards,
                      Projector Lamps World - Customer Service</span>
                      </td></tr>
                    </table>
                    </br><p>No comment...</p>

                    </div>
                </div>
            </div>
            <!-- -->


            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info2" title="LampeVideoProjecteur Infos">17 ao&ucirc;t 2011</a>
                </div>
                <div id="info2" class="accordion-body collapse">
                    <div class="accordion-inner">
                      <p>La plateforme de cr&eacute;ation de boutiques en ligne <a href="http://www.zlio.fr" target="_blank" title="LampeVideoProjecteur boutiques en ligne">ZLIO</a> annonce sa fermeture pour le 11 septembre 2011.</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info3"> 5 juillet 2011</a>
                </div>
                <div id="info3" class="accordion-body collapse">
                    <div class="accordion-inner">
                      <p> <span style="color:#FF7F00">Nouveau site</span> d&eacute;di&eacute; &agrave; la technologie LED dans la vid&eacute;projection : <a href="http://www.videoprojecteurled.com" target="_blank">VideoprojecteurLED.com</a>.</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info4"> 26 mai 2011</a>
                </div>
                <div id="info4" class="accordion-body collapse">
                    <div class="accordion-inner">
                      <p><span style="color:#FF7F00">Nouveau site</span> <a href="http://www.directlampes.com" target="_blank">DIRECTLAMPES.com</a>, proposant l'achat de lampes de vid&eacute;oprojecteur en importation &agrave; des prix tr&eacute;s int&eacute;ressants.</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info5" title="LampeVideoProjecteur info"> 15 avril 2011</a>
                </div>
                <div id="info5" class="accordion-body collapse">
                    <div class="accordion-inner">
                      <p><span style="color:#FF7F00">Nouveau site</span> <a href="http://www.rienquedeslampes.ma" target="_blank">www.rienquedeslampes.ma</a>, premier site de vente de lampes pour le Maroc.</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info6" title="LampeVideoProjecteur info"> 1er Janvier 2011</a>
                </div>
                <div id="info6" class="accordion-body collapse">
                    <div class="accordion-inner">
                      <p>Le site de vente de lampes <a href="http://www.rienquedeslampes.fr" target="_blank" title="LampeVideoProjecteur info">RIEN QUE DES LAMPES</a> offre d&eacute;sormais une garantie de 4 mois minimum sur toutes ses lampes.</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Fin accordeon -->
    </div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
      <div class="selecteur">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
      <div class="partenaire">
          <h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
          <form>
              <a href="partenariat.php" title="LampeVideoProjecteur partenariat"><div  class="btn-partenaire" onclick="location.href=partenariat.php"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
          <h3>Nos trois boutiques</h3>
          <div class="list_carousel">
        <ul id="foo0">
          <li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt=""  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
          <li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt=""  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour m&ecirc;me si la commande se fait avant 16h.</p>
                    </li>
          <li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt=""  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
        </ul>
        <div class="clearfix"></div>
      </div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->