<?php  
$this->layout()->title = 'Lampe-videoprojecteur.info - ANNUAIRE AUDIOVISUEL';
$this->headMeta()
                ->appendName('keywords', "annuaire audiovisuel")
                ->appendName('description', "Annuaire audiovisuel offert par www.lampe-videoprojecteur.info par échange de liens en dur - Site d'information sur le vidéoprojecteur et sa lampe - Page 1");
?>
<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.focuslight.fr" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="Focuslight" title="Focuslight" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->
<!-- Fil d'Ariane -->
<div class="ariane">
  <p>
      <a href="home" title="Lampe VideoProjecteur"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>&nbsp;&gt;&nbsp;
        <span>Annuaire audiovisuel</span>
    </p>
</div>
<!-- End Fil d'Ariane -->

<!-- Conteneur -->
<div class="containeur">
  <!-- Contenu -->
  <div class="contenu">
      <h1 class="titre_page">Annuaire audiovisuel</h1>
      <p class="intro">Pour augmenter la popularit&eacute; de votre site, ajoutez votre site sur cette page. La prise en compte est imm&eacute;diate. Un lien en retour est obligatoire. Consultez les explications en bas de page. Merci.</p>
        <strong class="deja">D&eacute;j&agrave; dans l'annuaire</strong>
        <ul class="list-annuaire">
          <li>
              <h4><a href="http://www.rienquedeslampes.fr/" title="Lampe VideoProjecteur RQDL" target="_blank">RQDL</a></h4>
                <p>Lampes pour vid&eacute;oprojecteurs &agrave; prix discount.</p>
            </li>
            <li>
              <h4><a href="http://www.focuslight.fr/" title="Focuslight" target="_blank">Achat de vidéoprojecteurs sur Focuslight.fr</a></h4>
                <p>Site de vente de projecteurs pour enseignement et entreprise. Les meilleures marques de la projection au meilleur prix.</p>
            </li>
            <li>
              <h4><a href="http://www.tableauxinteractifs.fr/equipement/tbi-vpi-ei-dmi-comment-choisir/" title="Choisir entre TNI/TBI, VPI, ETI ou DMI" target="_blank">Comment choisir son tbi sur Tableauxinteractifs.fr</a></h4>
                <p>Découvrez toutes les informations sur le tableau blanc interactif et les différentes solutions interactives en fonction de vos usages en enseignement ou en entreprise.</p>
            </li>
            <li>
              <h4><a href="http://www.tbi-direct.fr/ecran-tactile.html" title="ECRANS TACTILES INTERACTIFS" target="_blank">Ecran interactif sur tbi-direct.fr</a></h4>
                <p>Retrouvez unlarge choix d'écrans tactiles interactifs de grandes marques SMART, Mimio, Easypitch.<br/>Commandez la performance au juste prix.</p>
            </li>
            <li>
              <h4><a href="https://www.prointeractive.fr/" title="ProInteractive: vente de solutions interactives Promethean" target="_blank">Tbi promethean sur Prointercative.fr</a></h4>
                <p>Spécialiste des solutions interactives promethean et accessoires destinés pour l’enseignement. Vous y trouverez l’activboard, l’activpanel, l’activtable avec le logiciel intuitif Activinspire.</p>
            </li>
            <li>
              <h4><a href="http://www.ecran-interactif.net/" title="ecran-interactif" target="_blank">Spécialiste de l’écran interactif tactile</a></h4>
                <p>Le plus large choix d’écrans interactifs de technologie innovante en matière de points de contact, logiciel interactif, et système embarqué.</p>
            </li>
            <li>
              <h4><a href="http://www.lampevideoprojecteur.fr/lampe-epson.html" title="Lampe vid&eacute;oprojecteur Epson" target="_blank">Lampe vid&eacute;oprojecteur Epson</a></h4>
                <p>Lampes originales et original Inside pour vid&eacute;oprojecteurs. Premier en Europe.</p>
            </li>
            <li>
              <h4><a href="http://www.hotprojectorlamps.fr/" title="Lampe originale de vid&eacute;oprojecteur" target="_blank">Ampoule originale de vid&eacute;oprojecteur</a></h4>
                <p>Achat en ligne de lampes pour vid&eacute;oprojecteur Optoma, Epson, Mitsubishi,... </p>
            </li>
            <li>
              <h4><a href="http://www.geotraceur.fr/" title="Traceur GPS" target="_blank">Traceur GPS</a></h4>
                <p>D&eacute;veloppement et commercialisation de traceurs GPS et balises GPS en France.</p>
            </li>
            <li>
              <h4><a href="http://www.easyflowstudios.com/creation-logo.html" title="Cr&eacute;ation logo" target="_blank">Cr&eacute;ation logo</a></h4>
                <p>Cr&eacute;ation de logo sur mesure.</p>
            </li>
            <li>
              <h4><a href="http://www.e-fidelite.net/comparateur-gps" title="Comparateur gps" target="_blank">Comparateur gps</a></h4>
                <p>Meilleur comparateur gps du moment.</p>
            </li>
            <li>
              <h4><a href="http://buzzvideo.eu/videoscategory/humeur/" title="Vid&eacute;o humour" target="_blank">Vid&eacute;o humour</a></h4>
                <p>Vid&eacute;os buzz et humour, regardez des vid&eacute;os gratuitement sur buzzvideo.eu</p>
            </li>
            <li>
              <h4><a href="http://www.choufproduction.com/" title="Soci&eacute;t&eacute; de production" target="_blank">Soci&eacute;t&eacute; de production</a></h4>
                <p>Chouf Production est une soci&eacute;t&eacute; de production audiovisuelle situ&eacute;e &agrave; Bruxelles.</p>
            </li>
            <li>
              <h4><a href="http://www.alarmania.fr/" title="Alarme sans fil" target="_blank">Alarme sans fil</a></h4>
                <p>Alarmania propose toute une gamme de packs pour les systèmes de s&eacute;curisation.</p>
            </li>
            <li>
              <h4><a href="http://installations-home-cinema.eu/" title="Install-HC" target="_blank">Install-HC</a></h4>
                <p>Site consacr&eacute; aux Installations Home Cinema.</p>
            </li>
            <li>
              <h4><a href="http://auroreart.over-blog.com/categorie-928280.html" title="Art comme Audiovisuel" target="_blank">Art comme Audiovisuel</a></h4>
                <p>Actualit&eacute; artistiques et audiovisuelles. Des cr&eacute;ations &laquo; en tous arts &raquo;.</p>
            </li>
            <li>
              <h4><a href="http://www.affiche-cine.com/" title="Affiche-cine.com" target="_blank">Affiche-cine.com</a></h4>
                <p>Vente d'affiche de cin&eacute;ma : originales, anciennes et r&eacute;centes.</p>
            </li>
        </ul>
        <div class="souscription">
          <h5>Explication</h5>
            <p>Pour être partenaire et faire un échange de liens avec www.lampe-videoprojecteur.info, c'est très simple, il suffit de :
              <ol>
                  <li>Placer un lien vers la page <em>http://www.lampe-videoprojecteur.info</em> sur une page de votre site.</li>
                    <li>Remplir le formulaire ci-dessous.</li>
                </ol>
            Votre site sera effacé sans préavis :
              <ul>
                  <li>Si votre site n’a aucun rapport avec : Cinéma, DVD, Home-cinema, Musique, Spectacle, High-Tech, Projection, Ampoules et Lampes...</li>
                    <li>Si le lien est placé sur une page remplie de liens sans autre contenu réel</li>
                    <li>Si nous constatons que le lien de retour vers www.lampe-videoprojecteur.info n'est pus présent sur votre site (vérification automatique).</li>
                </ul>
                Merci de votre compréhension,
            </p>
            <h5>Le code à mettre sur votre site avant de commencer :</h5>
            <p>&lt;a href="http://www.lampe-videoprojecteur.info" target="_blank"&gt;Manuels de vidéoprojecteurs et comparateur de prix de lampes&lt;/a&gt;</p>
            <h5>Formulaire</h5>
            <p class="attention">Attention : avant de vous inscrire, vous devez placer un lien vers la page http://www.lampe-videoprojecteur.info sur une page de votre site.</p>
            <div class="formulaire">
            <form>
                    <div>
                        <label>Nom de votre site :</label>
                        <input type="text" value="" required />
                    </div>
                    <div>
                        <label>URL de votre site sans / à la fin </label>
                        <input type="text" value="" required />
                    </div>
                    <div>
                        <label>URL de la page de votre site où est affiché le lien vers <u>www.lampe-videoprojecteur.info</u></label>
                        <input type="text" value="" required />
                    </div>
                    <div>
                        <label>Description de vote site (80 caractères max.) </label>
                        <textarea maxlength="80" required></textarea>
                    </div>
                    <div>
                        <label>Votre adresse email </label>
                        <input type="email" value="" required />
                    </div>
                     <div>
                        <input type="submit" class="enregistrer" value="Enregistrer votre site" />
                    </div>
                    <div class="spacer"></div>
                </form>
            </div>
        </div>
    </div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
      <div class="selecteur">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
      <div class="partenaire">
          <h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
          <form>
              <a href="partenariat.php" title="Lampe VideoProjecteur partenariat"><div  class="btn-partenaire" onclick="location.href=annuaire-audiovisuel"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
          <h3>Nos trois boutiques</h3>
          <div class="list_carousel">
        <ul id="foo0">
          <li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt=""  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
          <li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt=""  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour même si la commande se fait avant 16h.</p>
                    </li>
          <li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt=""  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
        </ul>
        <div class="clearfix"></div>
      </div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->
