<?php  
$this->headMeta()
                ->appendName('keywords', "lampe videoprojecteur")
                ->appendName('description', "Le site d'informations sur le vidéoprojecteur et la lampe du projecteur. Prix, durée de vie, où acheter, infos nouveautés.");
?>

<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.projopourtous.com" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="projopourtous" title="projopourtous" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->
<!-- 3 blocs -->
<div class="box-line trois">
	<div class="three_blocs">
        <div class="partenaire">
        	<h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
         	<form>
                <a href="partenariat.php" title="Lampe VideoProjecteur devenir partenaire"><div  class="btn-partenaire" onclick="location.href=partenariat.php"/>Devenir partenaire</div></a>
            </form>
        </div>
        
        <div class="selecteur">
        	<h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <div>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">-- Modéle de vid&eacute;oprojecteur--</option>
                </select>
                <div style="margin-top:15px;">
                <div class="info-video" onclick="href_info_produit();" >Infos sur le vid&eacute;oprojecteur</div>
                <div class="prix-lampe" onclick="href_fiche_produit();">Prix de la lampe</div>
                </div>
            </div>
        </div>
        <div class="pour-nul">
        	<a href="infos-videoprojecteur.php" title="Vid&eacute;oprojecteur pour les nuls"><img src="images/pour-les-nul.jpg" alt="Vid&eacute;oprojecteur pour les nuls" width="220" height="222" /></a>
        </div>
        <div class="spacer"></div>
    </div>
</div>
<!-- End 3 blocs -->

<!-- Bienvenue -->
<div class="box-line bienvenue">
	<div class="welcome">
    	<h3>Bienvenue sur le site</h3>
        <h1>LAMPE VIDEOPROJECTEUR.INFO</h1>
        <p>Vous trouverez sur ce site les informations sur le vid&eacute;oprojecteur et sa lampe : Photos, prix, dur&eacute;e de vie, docs, manuels</p>
    </div>
</div>
<!-- End Bienvenue -->

<!-- Actus -->
<div class="box-line actus">
	<div class="box-actus">
        <h1>Nouveaut&eacute;s &amp; actualit&eacute;s !</h1>
        <div class="boite-a-actu">
        	<!-- 1 -->
        	<div class="article">
            	<img src="images/<?php echo $article[0]["image"];?>" width="215" height="215" alt="" />
                 <?php echo '<h4>'.$article[0]["titre"].'</h4>'; 
                        echo '<p>'.$article[0]["resume_article"].'</p>'; 
                 ?>
                <a href="nouveautes-videoprojecteurs-<?php echo $article[0]["constructeur"];?>.php">Lire la suite</a>
            </div>
            <!-- 2 -->
            <div class="article">
                <img src="images/<?php echo $article[1]["image"];?>" width="215" height="215" alt="" />
                <?php echo '<h4>'.$article[1]["titre"].'</h4>'; 
                        echo '<p>'.$article[1]["resume_article"].'</p>'; 
                 ?>
                <a href="nouveautes-videoprojecteurs-<?php echo $article[1]["constructeur"];?>.php">Lire la suite</a>
            </div>
            <!-- 3 -->
        	   <div class="article">
               <img src="images/<?php echo $article[2]["image"];?>" width="215" height="215" alt="" />
                <?php echo '<h4>'.$article[2]["titre"].'</h4>'; 
                        echo '<p>'.$article[2]["resume_article"].'</p>'; 
                 ?>
                <a href="nouveautes-videoprojecteurs-<?php echo $article[2]["constructeur"];?>.php">Lire la suite</a>
            </div>
            <?php if(isset($article[3])): ?>
            <!-- 4 -->
        	<div class="article">
                <img src="images/<?php echo $article[3]["image"];?>" width="215" height="215" alt="" />
                <?php echo '<h4>'.$article[3]["titre"].'</h4>'; 
                        echo '<p>'.$article[3]["resume_article"].'</p>'; 
                 ?>
                <a href="nouveautes-videoprojecteurs-<?php echo $article[3]["constructeur"];?>.php">Lire la suite</a>
            </div>
            <?php endif; ?>
            <?php if(isset($article[4])): ?>
        	<!-- 5 -->
        	<div class="article premier">
                <img src="images/<?php echo $article[4]["image"];?>" width="215" height="215" alt="" />
                <?php echo '<h4>'.$article[4]["titre"].'</h4>'; 
                        echo '<p>'.$article[4]["resume_article"].'</p>'; 
                 ?>
                <a href="nouveautes-videoprojecteurs-<?php echo $article[4]["constructeur"];?>.php">Lire la suite</a>
            </div>
            <?php endif; ?>
            <?php if(isset($article[5])): ?>
                <!-- 6 -->
            	<div class="article">
                    <img src="images/<?php echo $article[5]["image"];?>" width="215" height="215" alt="" />
                    <?php echo '<h4>'.$article[5]["titre"].'</h4>'; 
                            echo '<p>'.$article[5]["resume_article"].'</p>'; 
                     ?>
                    <a href="nouveautes-videoprojecteurs-<?php echo $article[5]["constructeur"];?>.php">Lire la suite</a>
                </div>
            <?php endif; ?>
            <?php if(isset($article[6])): ?>
                <!-- 7 -->
                <div class="article">
                    <img src="images/<?php echo $article[6]["image"];?>" width="215" height="215" alt="" />
                    <?php echo '<h4>'.$article[6]["titre"].'</h4>'; 
                            echo '<p>'.$article[6]["resume_article"].'</p>'; 
                     ?>
                    <a href="nouveautes-videoprojecteurs-<?php echo $article[6]["constructeur"];?>.php">Lire la suite</a>
                </div>
            <?php endif; ?>
            <?php if(isset($article[7])): ?>
                <!-- 8 -->
                <div class="article">
                    <img src="images/<?php echo $article[7]["image"];?>" width="215" height="215" alt="" />
                    <?php echo '<h4>'.$article[7]["titre"].'</h4>'; 
                            echo '<p>'.$article[7]["resume_article"].'</p>'; 
                     ?>
                    <a href="nouveautes-videoprojecteurs-<?php echo $article[7]["constructeur"];?>.php">Lire la suite</a>
                </div>
            <?php endif; ?>
            <div class="spacer"></div>
        </div>
    </div>
</div>
<!-- End Actus -->

