<?php  
$this->layout()->title = 'Infos Videoprojecteur';
$this->headMeta()
                ->appendName('keywords', "lampe vidéoprojecteur")
                ->appendName('description', "Infos vidéoprojecteur");
?>




<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.projopourtous.com" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="projopourtous" title="projopourtous" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->
<div class="ariane">
    <p>
        <a href="home" title="Lampe VideoProjecteur info"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>&nbsp;&gt;&nbsp;
        <span>Le vidéoprojecteur pour les nuls</span>
    </p>
</div>


<!-- Conteneur -->
<div class="containeur">
  <!-- Contenu -->
  <h1 class="titre_page">Le vid&eacute;oprojecteur pour les nuls</h1>
    <div class="contenu null">
            <table width="95%" border="0"  height="652px" style="margin-top:20px;margin-left:20px">

            <tr><td valign="top">
            <p align="justify">
            <span  style="color:#C0C0C0;"><b>Projecteur</b></span> n.m. Appareil envoyant au loin un puissant faisceau de rayons lumineux.<br>
            <span  style="color:#C0C0C0;"><b>Vid&eacute;o</b></span> adj. Se dit des signaux servant &agrave; la transmission d'images, et des appareils, des installations qui utilisent ces signaux.<br><br>

            Un vid&eacute;oprojecteur est donc un appareil qui reproduit une source vid&eacute;o et proj&egrave;te les images sur un &eacute;cran ou un mur blanc.<br><br>
            <font color="#FF7F00"><span  style="color:#EC8706;"><b>Pourquoi choisir un vid&eacute;oprojecteur ?</b></span></font>
            <br><br>
            C'est <u>la seule</u> solution pour avoir un -vraiment- grand &eacute;cran &agrave; la maison (voir plus bas).<br>
            En effet, n'importe quel vid&eacute;oprojecteur permet d'avoir une image de 2 m&egrave;tres de diagonale... et plus !<br>
            En second lieu, lorsque vous ne l'utilisez pas, vous n'aurez pas &agrave; voir un grand &eacute;cran &eacute;teint, le seul vid&eacute;oprojecteur a la taille d'une boite &agrave; chaussures.
            <br><br>
            <font color="#FF7F00"><span  style="color:#EC8706;"><b>Ce qu'il faut savoir :</b></span></font><br><br>
            <font color="#FF7F00">&#149;</font> Une source vid&eacute;o (tuner, d&eacute;codeur TNT, lecteur DVD) doit &egrave;tre connect&eacute;e au vid&eacute;oprojecteur<br>
            (Quelques rares mod&egrave;les ont un lecteur DVD ou un tuner int&eacute;gr&eacute;).<br><br>
            <font color="#FF7F00">&#149;</font> Ne comptez pas sur le vid&eacute;oprojecteur pour avoir du son.<br>
            Certes il est &eacute;quip&eacute; d'un petit haut-parleur, mais il faudra vous &eacute;quiper d'un syst&egrave;me de son.<br><br>

            <font color="#FF7F00">&#149;</font> La lampe est LE consommable du vid&eacute;oprojecteur, elle dure en moyenne normalement 2000 heures et co&ucirc;te 2 &agrave; 300 euros en moyenne. On ne laissera donc pas le vid&eacute;oprojecteur allum&eacute; comme une t&eacute;l&eacute;vision...

            <br><br>

            <font color="#FF7F00">&#149;</font> Vous devez avoir un peu de recul entre le mur (ou l'&eacute;cran) o&ugrave; vous projetez de projeter (joli, &ccedil;a !) et le vid&eacute;oprojecteur.<br>
            Plus le recul est important, plus vous pourrez avoir une grande image. par exemple :<br><br><center>

            <table border="0" cellpadding="5" cellspacing="5"><tr><td rowspan="2" align="center"><span  style="color:#C0C0C0;"><b>Distance entre le<br>vid&eacute;oprojecteur et l'&eacute;cran</b></span></td><td colspan="2" align="center"><span  style="color:#C0C0C0;"><b>Diagonale de l'image</b></span></td></tr>
            <tr><td align="center">format 4:3</td><td align="center">format 16:9</td></tr>

            <tr><td align="center">1,5 m</td><td align="center">1,07 m</td><td align="center">0,92 m</td></tr>
            <tr><td align="center">2 m</td><td align="center">1,32 m</td><td align="center">1,21 m</td></tr>
            <tr><td align="center">3 m</td><td align="center">1,98 m</td><td align="center">1,82 m </td></tr>
            <tr><td align="center">4 m</td><td align="center">2,64 m</td><td align="center">2,42 m</td></tr>
            <tr><td align="center">5 m</td><td align="center">3,30 m</td><td align="center">3,03 m</td></tr>
            <tr><td align="center">6 m</td><td align="center">3,96 m</td><td align="center">3,64 m</td></tr>
            <tr><td align="center">7 m</td><td align="center">4,62 m</td><td align="center">4,24 m</td></tr>
            <tr><td align="center">8 m</td><td align="center">5,29 m</td><td align="center">4,85 m</td></tr>
            <tr><td align="center">9 m</td><td align="center">5,95 m</td><td align="center">5,46 m</td></tr>
            </table>
            </center>

            <font color="#FF7F00"><span  style="color:#C0C0C0;"><b>Choisir son projecteur :</b></span></font><br><br>

            Les points les plus importants &agrave; prendre en compte sont :<br><br>
            <font color="#FF7F00">&#149;</font> La r&eacute;solution<br>
            Elle s'exprime par deux chiffres, par exemple (800 x600) le premier chiffre est le nombre de pixels horizontaux et le second le nombre de pixels verticaux. Plus ces nombres sont &eacutelev&eacute;s, plus les d&eacute;tails sont nets.<br><br>

            <font color="#FF7F00">&#149;</font> La luminosit&eacute;<br>
            Elle s'exprime en Lumens ANSI, et plus elle est importante plus vous pourrez utiliser le projecteur sans faire le noir dans la pi&egrave;ce. Si vous pr&eacute;voyez une grande taille d'image (3m et +), il vous faut une luminosit&eacute; &eacute;lev&eacute;e.<br><br>

            <font color="#FF7F00">&#149;</font> Le contraste<br>
            Le rapport de contraste (par exemple 1000:1 ou 2000:1) exprime le rapport entre les valeurs de noir et de blanc. Pour une utilisation dans le noir en home-cinema, un rapport de 800:1 est suffisant.<br><br>

            <font color="#FF7F00">&#149;</font> Le bruit<br>
            Les ventilateurs des vid&eacute;oprojecteurs tournent en permanence, si l'appareil est situ&eacute; tout pr&egrave;s de vous, le bruit peut s'av&eacute;rer tr&egrave;s g&ecirc;nant. Les appareils modernes sont de plus en plus sliencieux, mais &ccedil;a peut &ecirc;tre un crit&egrave;re de choix si vous h&eacute;sitez entre deux mod&egrave;les.<br><br>

            <font color="#FF7F00">&#149;</font> Le prix de la lampe<br>
            Cela ne doit pas &ecirc;tre un crit&egrave;re essentiel pour faire votre choix, mais il ne faut pas le n&eacute;gliger. En effet, &agrave; performances et prix identiques, entre deux vid&eacute;oprojecteurs dont les lampes co&ucirc;tent du simple au double, lequel choisirez-vous ?<br><br>

            <font color="#FF7F00"><span  style="color:#EC8706;"><b>Pour aller plus loin...</b></span></font><br><br>
            <img src="images/fleche.gif">&nbsp;<a href="http://www.projopourtous.com/boutique/page_5.cfm?code_lg=lg_fr" target="_blank" title="ProjoPourTous.com, le sp&eacute;cialiste fran&ccedil;ais du vid&eacute;oprojecteur sur Internet" OnMouseOver="self.status='ProjoPourTous.com, le sp&eacute;cialiste fran&ccedil;ais du vid&eacute;oprojecteur sur Internet';return true;" OnMouseOut="self.status=''; return true;"><font  color="#0000C0">ProjoPourTous.com, le sp&eacute;cialiste fran&ccedil;ais du vid&eacute;oprojecteur sur Internet</a></font>
            </p>
            </td></tr>
          </table>
      
    </div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
        <div class="selecteur" style="margin-top:0px;">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
        <div class="partenaire">
            <h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
            <form>
                <a href="partenariat.php" title="Lampe VideoProjecteur devenir partenaire"><div  class="btn-partenaire" onclick="location.href=annuaire-audiovisuel"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
            <h3>Nos trois boutiques</h3>
            <div class="list_carousel">
                <ul id="foo0">
                    <li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt="Lampe VideoProjecteur partenariat"  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt="Lampe VideoProjecteur partenariat"  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour même si la commande se fait avant 16h.</p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt="Lampe VideoProjecteur partenariat"  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->


