<?php  
$this->layout()->title = 'Lampe vidéoprojecteur';
$this->headMeta()
                ->appendName('keywords', "lampe vidéoprojecteur")
                ->appendName('description', "La lampe de vidéoprojecteur");
?>
<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.projopourtous.com" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="projopourtous" title="projopourtous" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->
<!-- Fil d'Ariane -->
<div class="ariane">
	<p>
    	<a href="home" title="Lampe VideoProjecteur"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>&nbsp;&gt;&nbsp;
        <span>Infos sur les lampes de vid&eacute;oprojecteurs par marques</span>
    </p>
</div>
<!-- End Fil d'Ariane -->

<!-- Conteneur -->
<div class="containeur">
	<!-- Contenu -->
	<div class="contenu">
    	<h1 class="titre_page">Le vid&eacute;oprojecteur et sa lampe</h1>
        <!-- D&eacute;but accordeon -->
    	<div class="accordion acc" id="accordion2">
        	<!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info1" title="Lampe VideoProjecteur infos">La lampe du vid&eacute;oprojecteur</a>
                </div>
                <div id="info1" class="accordion-body collapse in">
                    <div class="accordion-inner">
                    	<p style="text-align:justify;">La lampe du <a href="http://www.lampe-videoprojecteur.info/videoprojecteur.php" title="">vid&eacute;oprojecteur</a> produit une lumi&egrave;re blanche qui est dirig&eacute;e vers les miroirs de la puce DMD.</p>
						<p>Cette lumi&egrave;re blanche (qui contient toutes les couleurs, comme celle du jour) traverse la roue chromatique divis&eacute;e en segments rouge, vert et bleu. </p>
						<p style="text-align:justify;">Les miroirs du circuit DMD (command&eacute; par le processeur) pivotent pour renvoyer la lumi&egrave;re vers l'&eacute;cran, ou ne pas la renvoyer lorsqu'un pixel doit rester noir.</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info2" title="Lampe VideoProjecteur infos">Manipulation</a>
                </div>
                <div id="info2" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>Le remplacement du module de lampe du vid&eacute;oprojecteur est rapide, facile et ne n&eacute;cessite ni aptitudes ni connaissances particuli&egrave;res. L'ampoule est prot&eacute;g&eacute;e dans son module. C'est la raison pour laquelle il est conseill&eacute; de ne remplacer la lampe que par le module de lampe complet (sauf sp&eacute;cifications contraires dues au fabricant du vid&eacute;oprojecteur). </p>
						<p>En revanche, ne remplacer que l'ampoule (bulbe) est nettement plus d&eacute;licat : Ne jamais toucher l'ampoule avec les doigts, l'usage d'un tissu ou de gants est recommand&eacute; pour toute manipulation en contact avec le verre de l'ampoule.</p>
						<p>Nettoyez les filtres &agrave; air du projecteur. Leur blocage cause une surchauffe de la lampe qui entraine sa d&eacute;faillance. Les fabricants peuvent en tester les causes et invalidera toute garantie. Assurez-vous toujours du bon &eacute;coulement d'air autour du projecteur.</p> 
						<p>Si vous remplacez une ampoule &agrave; l'int&eacute;rieur m&ecirc;me du module de logement, assurez-vous que ses bornes ne sont pas sur-serr&eacute;es afin d'&eacute;viter une fracture de la c&eacute;ramique et, par cons&eacute;quent, entraîner une r&eacute;duction de l'isolation &eacute;lectronique de la lampe. D'une autre part, un sous-serrage des bornes peut contribuer aux conditions n&eacute;cessaires au jaillissement d'un arc &eacute;lectrique et de ce fait entrainer une surcharge &eacute;lectrique sur le ballast pouvant r&eacute;sulter en une panne. </p>
						<p>Pour installer les ampoules, les lampes doivent &ecirc;tre positionn&eacute;es correctement. On a tendance &agrave; s'arr&ecirc;ter au premier signe de r&eacute;sistance, cependant continuez &agrave; presser doucement jusqu'&agrave; ce que la lampe soit bien emboit&eacute;e. </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info3" title="Lampe VideoProjecteur infos">Eteindre le projecteur</a>
                </div>
                <div id="info3" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>Utilisez toujours la t&eacute;l&eacute;commande du projecteur pour l'&eacute;teindre. Ne d&eacute;brancher jamais le projecteur pour l'&eacute;teindre. Dans l'absence d'images &agrave; projeter, le projecteur adoptera un mode automatique de refroidissement et actionnera son ventilateur afin de refroidir d'une mani&egrave;re contr&ocirc;l&eacute;e sa lampe. La temp&eacute;rature d'une lampe en &eacute;tat op&eacute;rationnel atteint des milliers de degr&eacute;s. D&eacute;brancher un projecteur sans permettre &agrave; ce dernier de contr&ocirc;ler le refroidissement de sa lampe (comme indiqu&eacute; ci-dessus) causera un refroidissement in&eacute;gal de la surface de la lampe, et aboutira &agrave; son usure pr&eacute;matur&eacute;e et ce sera la panne. </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info4">Chocs et vibrations</a>
                </div>
                <div id="info4" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>Le non-fonctionnement d'une lampe peut &ecirc;tre caus&eacute; par au choc physique (m&eacute;canique). Un filament de lampe chaud est tr&egrave;s fragile, vous devriez donc toujours vous assurer que l'appareil est &eacute;teint et attendre le refroidissement de la lampe. </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info5">Le mode Economie</a>
                </div>
                <div id="info5" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>Si votre projecteur est &eacute;quip&eacute; d'un commutateur de lampe "Normal/Eco", vous pouvez prolonger la dur&eacute;e de vie moyenne de la lampe en utilisant la position "Eco" d&egrave;s que possible. </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info6">Nettoyage du vid&eacute;oprojecteur</a>
                </div>
                <div id="info6" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>D&eacute;montez et aspirez les filtres comme indiqu&eacute; dans votre notice d'utilisation:
							<ul>
                        		<li>Une fois par an si le vid&eacute;oprojecteur fonctionne dans un environnement sain.</li>
								<li>Tous les 3 mois si le vid&eacute;oprojecteur fonctionne dans un environnement poussi&eacute;reux ou si vous fumez.</li>
                            </ul>
N'utilisez pas de bombe &agrave; air comprim&eacute; vers l'int&eacute;rieur de l'appareil, vous risqueriez de disperser la poussi&egrave;re. </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info7">La dur&eacute;e de vie d'une lampe</a>
                </div>
                <div id="info7" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>La <a href="http://www.lampe-videoprojecteur.info/duree-lampe-videoprojecteur-Epson.html" title="">dur&eacute;e de vie de la lampe de votre projecteur</a>  est donn&eacute;e &agrave; titre indicatif par le fabricant et c'est un temps de vie moyen (en mode &eacute;conomique si disponible). Elle durera plus longtemps si vous respectez le temps de refroidissement (voir ci-dessus Eteindre le projecteur) et les pr&eacute;cautions d'usage. Elle durera moins longtemps dans un environnement poussi&eacute;reux ou de fum&eacute;e de cigarette, pensez donc &agrave; nettoyer r&eacute;guli&egrave;rement le filtre du projecteur.</p>
<p>Afin d'assurer une dur&eacute;e de vie plus longue de la lampe du projecteur, veillez &agrave; ne jamais couper l'alimentation du vid&eacute;oprojecteur pendant la phase de refroidissement apr&egrave;s extinction de la lampe, ventilateur en fonctionnement. L'utilisation d'un onduleur peut &ecirc;tre tr&egrave;s utile si vous subissez souvent des coupures de courant &eacute;lectrique, afin de ne pas couper l'alimentation du ventilateur du projecteur. 
</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info8">Le compteur horaire de votre projecteur</a>
                </div>
                <div id="info8" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>Il vous indiquera la dur&eacute;e d'utilisation en heures et donc le moment de changer la lampe. Surtout ne pensez pas pouvoir faire des &eacute;conomies en essayant d'aller plus loin : la lampe pourrait imploser dans le projecteur et les d&eacute;g&acirc;ts ne seraient pas couverts par la garantie. </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info9">La fin de la lampe</a>
                </div>
                <div id="info9" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>Une luminosit&eacute; en baisse et une teinte de l'image jaune sont les signes de fin de vie d'une lampe. Il faut donc penser &agrave; la remplacer, m&ecirc;me si elle n'a pas atteint la dur&eacute;e de vie pr&eacute;vue.</p>
						<p>A ce moment, si la lampe n'est pas chang&eacute;e, elle risque de finir par exploser, l'ampoule de verre ne supportant plus la temp&eacute;rature des &eacute;lectrodes qui se sont rapproch&eacute;es des extr&eacute;mit&eacute;s de la lampe. Cette explosion n'endommagera pas le projecteur si les d&eacute;bris de verre sont soigneusement nettoy&eacute;s.</p>

                    </div>
                </div>
            </div>
            <!-- -->
        </div>
        <!-- Fin accordeon -->
    </div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
    	<div class="selecteur">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
    	<div class="partenaire">
        	<h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
         	<form>
            	<a href="partenariat.php"><div  class="btn-partenaire" onclick="location.href=partenariat.php"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
        	<h3>Nos trois boutiques</h3>
        	<div class="list_carousel">
				<ul id="foo0">
					<li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt=""  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
					<li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt=""  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour m&ecirc;me si la commande se fait avant 16h.</p>
                    </li>
					<li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt=""  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
				</ul>
				<div class="clearfix"></div>
			</div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->
