<?php  
$this->layout()->title = 'Lampes videoprojecteurs';
$this->headMeta()
                ->appendName('keywords', "lampe vidéoprojecteur")
                ->appendName('description', "Infos lampe vidéoprojecteur");
?>
<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.projopourtous.com" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="projopourtous" title="projopourtous" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->

<!-- Fil d'Ariane -->
<div class="ariane">
  <p>
      <a href="reference-lampe-videoprojecteur-SONY.html"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>&nbsp;&gt;&nbsp;
        <span>Marques de lampes et de vid&eacute;oprojecteurs</span>
    </p>
</div>
<!-- End Fil d'Ariane -->

<!-- Conteneur -->
<div class="containeur">
  <!-- Contenu -->
  <div class="contenu">
      <h1 class="titre_page">Marques de lampes et de vid&eacute;oprojecteurs</h1>
      <p>Vous trouverez ici toutes les informations par marques sur les vidéoprojecteurs et sur les lampes de rechange : durée de vie, spécifications des lampes, manuels d’utilisation, etc. </p>
      <p>En plus d’être un site spécialisé dans l’information des vidéoprojecteurs et des lampes, lampe-videoprojecteur.info vous donne aussi la possibilité de comparer le prix des lampes de remplacement de vidéoprojecteur pour un achat économique. </p>
        <!-- Liste des marques -->
        <div class="box-mark">
            <ul class="mark-list">
                <li>
                    <a href="reference-lampe-videoprojecteur-EPSON.html" title="EPSON"><img src="images/marque/1.gif" width="100" height="100" alt="EPSON" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-EPSON.html" title="EPSON">EPSON</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-HITACHI.html" title="HITACHI"><img src="images/marque/2.gif" width="100" height="100" alt="HITACHI" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-HITACHI.html" title="HITACHI">HITACHI</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-MITSUBISHI.html" title="MITSUBISHI"><img src="images/marque/3.gif" width="100" height="100" alt="MITSUBISHI" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-MITSUBISHI.html" title="HITACHI">MITSUBISHI</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-NEC.html" title="NEC"><img src="images/marque/4.gif" width="100" height="100" alt="NEC" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-NEC.html" title="MITSUBISHI">MITSUBISHI</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-InFOCUS.html" title="InFOCUS"><img src="images/marque/5.gif" width="100" height="100" alt="InFOCUS" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-InFOCUS.html" title="InFOCUS">InFOCUS</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Optoma.html" title="Optoma"><img src="images/marque/6.gif" width="100" height="100" alt="Optoma" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Optoma.html" title="Optoma">Optoma</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Panasonic.html" title="Panasonic"><img src="images/marque/7.gif" width="100" height="100" alt="Panasonic" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Panasonic.html" title="Panasonic">Panasonic</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-SANYO.html" title="SANYO"><img src="images/marque/8.gif" width="100" height="100" alt="SANYO" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-SANYO.html" title="SANYO">SANYO</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-TOSHIBA.html" title="TOSHIBA"><img src="images/marque/9.gif" width="100" height="100" alt="TOSHIBA" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-TOSHIBA.html" title="TOSHIBA">TOSHIBA</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-3M.html" title="3M"><img src="images/marque/10.gif" width="100" height="100" alt="3M" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-3M.html" title="3M">3M</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Acer.html" title="Acer"><img src="images/marque/11.gif" width="100" height="100" alt="Acer" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Acer.html" title="Acer">Acer</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-AK.html" title="AK"><img src="images/marque/12.gif" width="100" height="100" alt="AK" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-AK.html" title="AK">AK</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-ASK Proxima.html" title="ASK Proxima"><img src="images/marque/13.gif" width="100" height="100" alt="ASK Proxima" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-ASK Proxima.html" title="ASK Proxima">ASK Proxima</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-BARCO.html" title="BARCO"><img src="images/marque/14.gif" width="100" height="100" alt="BARCO" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-BARCO.html" title="BARCO">BARCO</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-BENQ.html" title="BENQ"><img src="images/marque/15.gif" width="100" height="100" alt="BENQ" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-BENQ.html" title="BENQ">BENQ</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Canon.html" title="Canon"><img src="images/marque/16.gif" width="100" height="100" alt="Canon" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Canon.html" title="Canon">Canon</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-CASIO.html" title="CASIO"><img src="images/marque/17.gif" width="100" height="100" alt="CASIO" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-CASIO.html" title="CASIO">CASIO</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-CHRISTIE.html" title="CHRISTIE"><img src="images/marque/18.gif" width="100" height="100" alt="CHRISTIE" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-CHRISTIE.html" title="CHRISTIE">CHRISTIE</a>
                </li>
                <li>
                <a href="reference-lampe-videoprojecteur-COMPAQ.html" title="COMPAQ"><img src="images/marque/19.gif" width="100" height="100" alt="COMPAQ" /></a>
                <a class="name-mark" href="reference-lampe-videoprojecteur-COMPAQ.html" title="COMPAQ">COMPAQ</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-DELL.html" title="DELL"><img src="images/marque/20.gif" width="100" height="100" alt="DELL" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-DELL.html" title="HITACHI">DELL</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Dream Vision.html" title="Dream Vision"><img src="images/marque/21.gif" width="100" height="100" alt="Dream Vision" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Dream Vision.html" title="Dream Vision">Dream Vision</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-EIKI.html" title="EIKI"><img src="images/marque/22.gif" width="100" height="100" alt="EIKI" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-EIKI.html" title="EIKI">EIKI</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-ELECTROHOME.html" title="ELECTROHOME"><img src="images/marque/23.gif" width="100" height="100" alt="ELECTROHOME" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-ELECTROHOME.html" title="ELECTROHOME">ELECTROHOME</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-FUJITSU.html" title="FUJITSU"><img src="images/marque/24.gif" width="100" height="100" alt="FUJITSU" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-FUJITSU.html" title="HITACHI">HITACHI</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-FUJITSU SIEMENS.html" title="FUJITSU SIEMENS"><img src="images/marque/25.gif" width="100" height="100" alt="FUJITSU SIEMENS" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-FUJITSU SIEMENS.html" title="FUJITSU SIEMENS">FUJITSU SIEMENS</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Geha.html" title="Geha"><img src="images/marque/26.gif" width="100" height="100" alt="Geha" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Geha.html" title="HITACHI">Geha</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-HP.html" title="HP"><img src="images/marque/27.gif" width="100" height="100" alt="HP" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-HP.html" title="HP">HP</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-IBM.html" title="IBM"><img src="images/marque/28.gif" width="100" height="100" alt="IBM" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-IBM.html" title="IBM">IBM</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-LG.html" title="LG"><img src="images/marque/29.gif" width="100" height="100" alt="LG" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-LG.html" title="LG">LG</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Marantz.html" title="Marantz"><img src="images/marque/30.gif" width="100" height="100" alt="Marantz" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Marantz.html" title="Marantz">Marantz</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-PHILIPS.html" title="PHILIPS"><img src="images/marque/31.gif" width="100" height="100" alt="PHILIPS" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-PHILIPS.html" title="PHILIPS">PHILIPS</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-PLUS.html" title="PLUS"><img src="images/marque/32.gif" width="100" height="100" alt="PLUS" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-PLUS.html" title="PLUS">PLUS</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Projection Design.html" title="Projection Design"><img src="images/marque/33.gif" width="100" height="100" alt="Projection Design" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Projection Design.html" title="Projection Design">Projection Design</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-ASK Proxima.html" title="ASK Proxima"><img src="images/marque/34.gif" width="100" height="100" alt="ASK Proxima" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-ASK Proxima.html" title="ASK Proxima">ASK Proxima</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-SAGEM.html" title="SAGEM"><img src="images/marque/35.gif" width="100" height="100" alt="SAGEM" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-SAGEM.html" title="SAGEM">SAGEM</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-SAMSUNG.html" title="SAMSUNG"><img src="images/marque/36.gif" width="100" height="100" alt="SAMSUNG" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-SAMSUNG.html" title="SAMSUNG">SAMSUNG</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-SHARP.html" title="SHARP"><img src="images/marque/37.gif" width="100" height="100" alt="SHARP" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-SHARP.html" title="SHARP">SHARP</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-SIM2.html" title="SIM2"><img src="images/marque/38.gif" width="100" height="100" alt="SIM2" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-SIM2.html" title="SIM2">SIM2</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-SONY.html" title="SONY"><img src="images/marque/39.gif" width="100" height="100" alt="SONY" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-SONY.html" title="SONY">SONY</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-THOMSON.html" title="THOMSON"><img src="images/marque/40.gif" width="100" height="100" alt="THOMSON" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-THOMSON.html" title="THOMSON">THOMSON</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-ViewSonic.html" title="ViewSonic"><img src="images/marque/41.gif" width="100" height="100" alt="ViewSonic" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-ViewSonic.html" title="ViewSonic">ViewSonic</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-VIVITEK.html" title="VIVITEK"><img src="images/marque/42.gif" width="100" height="100" alt="VIVITEK" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-VIVITEK.html" title="VIVITEK">VIVITEK</a>
                </li>
                <li>
                    <a href="reference-lampe-videoprojecteur-Yamaha.html" title="YAMAHA"><img src="images/marque/43.gif" width="100" height="100" alt="YAMAHA" /></a>
                    <a class="name-mark" href="reference-lampe-videoprojecteur-Yamaha.html" title="YAMAHA">YAMAHA</a>
                </li>
                <li class="spacer"></li>
            </ul>
        </div>
        <!-- Fin accordeon -->
    </div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
        <div class="selecteur">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
        <div class="partenaire">
            <h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
            <form>
                <a href="partenariat.php"><div  class="btn-partenaire" onclick="location.href=annuaire-audiovisuel"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
            <h3>Nos trois boutiques</h3>
            <div class="list_carousel">
                <ul id="foo0">
                    <li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt=""  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt=""  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour même si la commande se fait avant 16h.</p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt=""  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->

