<?php  
$this->layout()->title = 'Lampe vidéoprojecteur mentions legales';
$this->headMeta()
                ->appendName('keywords', "lampe vidéoprojecteur mentions legales")
                ->appendName('description', "La lampe de vidéoprojecteur mentions legales");
?>
<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.projopourtous.com" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="projopourtous" title="projopourtous" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->
<!-- Fil d'Ariane -->
<div class="ariane">
	<p>
    	<a href="home" title="Lampe VideoProjecteur"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>&nbsp;&gt;&nbsp;
        <span>Mentions l&eacute;gales</span>
    </p>
</div>
<!-- End Fil d'Ariane -->

<!-- Conteneur -->
<div class="containeur">
	<!-- Contenu -->
	<div class="contenu">
    	<h1 class="titre_page">Mentions l&eacute;gales</h1>
        <!-- D&eacute;but accordeon -->
    	<div class="accordion acc" id="accordion2">
        	<!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info1" title="Lampe VideoProjecteur infos">Description des services</a>
                </div>
                <div id="info1" class="accordion-body collapse in">
                    <div class="accordion-inner">
						<p>
							<a href="http://www.lampe-videoprojecteur.info">http://www.lampe-videoprojecteur.info</a> vous propose gratuitement et sans inscription pr&eacute;alable diff&eacute;rents services tels que des fiches techniques sur les vid&eacute;oprojecteurs, des articles traitant de l&rsquo;actualit&eacute; et des nouveaut&eacute;s de la&nbsp; vid&eacute;oprojection et des fiches produits provenant de 3 marchands&nbsp;; rienquedeslampes.fr, lampevideoprojecteur.fr, hotprojectorlamps.fr.
						</p>
						<p>
							Les r&eacute;sultats qui sont affich&eacute;s sur le site ne sont pas exhaustifs de l&rsquo;ensemble des offres disponibles sur Internet et proviennent des donn&eacute;es fournies par les marchands r&eacute;f&eacute;renc&eacute;s.
						</p>
						<p>
							L&rsquo;ordre de pr&eacute;sentation des offres est class&eacute; par popularit&eacute; et le r&eacute;sultat des donn&eacute;es peut d&eacute;pendre de plusieurs facteurs en fonction du type de recherche que vous effectuez.
						</p>
						<p>
							Les Marchands sont des tierces parties. Lorsque vous utilisez les services propos&eacute;s par un Marchand, lorsque vous vous rendez sur le site &agrave; partir de <a href="http://www.lampe-videoprojecteur.info">http://www.lampe-videoprojecteur.info</a>&nbsp; pour y acheter un bien ou un service, vous vous soumettez &agrave; ses conditions d&rsquo;utilisation, lampe-videoprojecteur.info &eacute;tant &eacute;tranger &agrave; vos relations avec ce marchand.
						</p>
						<p>
							En cas de commande d&rsquo;un de ces produits et suite &agrave; l&rsquo;acceptation de cette commande par le Marchand, le prix indiqu&eacute; sur le site du Marchand lors de votre achat sera celui effectivement appliqu&eacute;.
						</p>
						<p>
							Par ailleurs, lampe-videoprojecteur.info s&rsquo;engage &agrave; mettre &agrave; jour, toutes les informations relative aux produits propos&eacute;s par les marchands r&eacute;f&eacute;renc&eacute;s sur le site (r&eacute;f&eacute;rences, prix, d&eacute;lai de livraison, tarif de livraison).
						</p>
						<p>
							Le site lampe-videoprojecteur.info est destin&eacute; aux consommateurs finaux qui d&eacute;sirent s&rsquo;informer ou achetez en ligne.
						</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info2" title="Lampe VideoProjecteur infos">Droit d&rsquo;auteur</a>
                </div>
                <div id="info2" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>
							La charte graphique du site, les donn&eacute;es, le graphisme, les images et toutes informations de ce site sont soumis au droit d&rsquo;auteur r&eacute;gis par les conventions internationales sur les droits d&rsquo;auteur. Toute reproduction, imitation ou modification partielle ou int&eacute;grale ne peuvent &ecirc;tre r&eacute;alis&eacute;e qu&rsquo;apr&egrave;s l&rsquo;autorisation de l&rsquo;entreprise.
						</p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info3" title="Lampe VideoProjecteur infos">Commentaires & Espace Actualités</a>
                </div>
                <div id="info3" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>
                    		Les clients peuvent s’exprimer librement sur les produits ou les services des sites internet sur lesquels s’est effectué l’achat. 
                    	 </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info4">Litiges</a>
                </div>
                <div id="info4" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>
                    		lampe-videoprojecteur.info ne peut être tenu responsable des informations communiquées par les  Marchands référencés relative à leurs offres de produits ou de services. Tout problème de défectuosité du produit ou de retard dans la livraison ne sera pas à la charge de lampe-videoprojecteur.info.
                    	 </p>
                    </div>
                </div>
            </div>
            <!-- -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle info-titre" data-toggle="collapse" data-parent="#accordion2" href="#info5">Contenus illicites ou litigieux</a>
                </div>
                <div id="info5" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<p>
							Si vous constatez la pr&eacute;sence sur notre site ou nos services d&rsquo;un contenu illicite ou probl&eacute;matique, nous vous remercions de bien vouloir nous le signaler &agrave; l&rsquo;adresse suivante&nbsp;: <a href="mailto:contact@lampe-videoprojecteur.info">contact@lampe-videoprojecteur.info</a></p>
						<p>
							Vous devriez dans ces cas-l&agrave;, communiquer votre&nbsp;:</p>
						<ul>
							<li>
								Nom et pr&eacute;nom
							</li>
							<li>
								Un descriptif du contenu que vous jugez illicite
							</li>
							<li>
								Les raisons pour lesquelles vous pensez que ce contenu est inappropri&eacute;
							</li>
						</ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Fin accordeon -->
    </div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
    	<div class="selecteur">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
    	<div class="partenaire">
        	<h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
         	<form>
            	<a href="partenariat.php"><div  class="btn-partenaire" onclick="location.href=partenariat.php"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
        	<h3>Nos trois boutiques</h3>
        	<div class="list_carousel">
				<ul id="foo0">
					<li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt=""  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
					<li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt=""  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour m&ecirc;me si la commande se fait avant 16h.</p>
                    </li>
					<li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt=""  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
				</ul>
				<div class="clearfix"></div>
			</div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->