<?php 
$this->layout()->title = "Nouveautés Videoprojecteurs 20".date('y'); 
$this->headMeta()
                ->appendName('keywords', "nouveautes vidéoprojecteur")
                ->appendName('description', "Toutes les nouveautés vidéoprojecteurs 20".date('y'));
?>
<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.projopourtous.com" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="projopourtous" title="projopourtous" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->
<div class="ariane">
    <p>
        <a href="home"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>&nbsp;&gt;&nbsp;
        <span>Nouveaut&eacute;s Videoprojecteurs par marques <?php //echo date('Y'); ?></span>
    </p>
</div>

<!-- Conteneur -->
<div class="containeur">
  <!-- Contenu -->
  <div class="contenu">
      <h1 class="titre_page">Nouveaut&eacute;s Videoprojecteurs par marques <?php //echo date('Y'); ?></h1>
        <!-- Liste des marques -->
        <div class="box-mark">
            <ul class="mark-list">
                <li>
                    <a href="achat-en-ligne.php" title="Achat videoprojecteur lampe">
                    <img src="img/images/acheter.gif" border="0" alt="Achat videoprojecteur lampe"></a>
                    <a class="name-mark" href="achat-en-ligne.php" title="EPSON">Achats en ligne</a>
                </li>
                <?php
                    foreach ($article as $key => $value):
                    if($const == $value["constructeur"])continue;
                ?>
            
                <li>
                    <a class="name-mark" href="liste-articles-<?php echo $value["constructeur"];?>.php?marque=<?php echo $value["constructeur"];?>" title="lampe videoprojecteur <?php echo $value["constructeur"];?>">
                        <!--<div><?php //echo $value["constructeur"];?></div>-->
                        <img src="img/img-lampe/lampe-<?php echo ucfirst($value["constructeur"]);?>.gif" border="0" alt="Achat videoprojecteur lampe"><?php echo strtoupper($value["constructeur"]);?>
                    </a>
                </li>                     
                <?php $const = $value["constructeur"]; endforeach;  ?>
                <li class="spacer"></li>
            </ul>
            <!-- <ul class="mark-list">
                <li>
                    <a href="achat-en-ligne.php" title="Achat videoprojecteur lampe">
                    <img src="img/images/acheter.gif" border="0" alt="Achat videoprojecteur lampe"></a>
                    <a class="name-mark" href="achat-en-ligne.php" title="EPSON">Achats en ligne</a>
                </li>
                <li>
                  <a href="nouveautes-videoprojecteurs-acer.php" title="lampe videoprojecteur Acer">
                  <img src="img/img-lampe/lampe-Acer.gif" border="0" alt="Nouveautés videoprojecteurs Acer"></a>
                    <a class="name-mark" href="nouveautes-videoprojecteurs-Acer.php" title="Acer">Acer</a>
                </li>
                <li>
                    <a href="nouveautes-videoprojecteurs-benq.php" title="lampe videoprojecteur Benq">
                    <img src="img/img-lampe/lampe-BenQ.gif" border="0" alt="Nouveautés videoprojecteurs Benq"></a>
                    <a class="name-mark" href="nouveautes-videoprojecteurs-Benq.php" title="Benq">Benq</a>
                </li>
                <li>
                    <a href="nouveautes-videoprojecteurs-casio.php" title="lampe videoprojecteur Casio">
                    <img src="img/img-lampe/lampe-Casio.gif" border="0" alt="Nouveautés videoprojecteurs Casio"></a>
                    <a class="name-mark" href="nouveautes-videoprojecteurs-Casio.php" title="Casio">Casio</a>
                </li>
                <li>
                    <a href="nouveautes-videoprojecteurs-christie.php" title="lampe videoprojecteur Christie"><img src="img/img-lampe/lampe-Christie.gif" border="0" alt="Nouveautés videoprojecteurs Christie"></a>
                    <a class="name-mark" href="nouveautes-videoprojecteurs-Christie.php" title="Christie">Christie</a>
                </li>
                <li>
                  <a href="nouveautes-videoprojecteurs-mitsubishi.php" title="lampe videoprojecteur Mitsubishi">
                  <img src="img/img-lampe/lampe-Mitsubishi.gif" border="0" alt="Nouveautés videoprojecteurs Mitsubishi"></a>
                  <a class="name-mark" href="nouveautes-videoprojecteurs-Mitsubishi.php" title="Mitsubishi">Mitsubishi</a>
                </li>
                <li>
                    <a href="nouveautes-videoprojecteurs-panasonic.php" title="lampe videoprojecteur Panasonic"><img src="img/img-lampe/lampe-Panasonic.gif" border="0" alt="Nouveautés videoprojecteurs Panasonic"></a>
                    <a class="name-mark" href="nouveautes-videoprojecteurs-Panasonic.php" title="Panasonic">Panasonic</a>
                </li>
                <li>
                  <a href="nouveautes-videoprojecteurs-sanyo.php" title="lampe videoprojecteur Sanyo">
                  <img src="img/img-lampe/lampe-Sanyo.gif" border="0" alt="Nouveautés videoprojecteurs Sanyo"></a>
                    <a class="name-mark" href="nouveautes-videoprojecteurs-SANYO.php" title="SANYO">Sanyo</a>
                </li>
                <li>
                    <a href="nouveautes-videoprojecteurs-sony.php" title="lampe videoprojecteur Sony">
                    <img src="img/img-lampe/lampe-Sony.gif" border="0" alt="Nouveautés videoprojecteurs Sanyo"></a>
                    <a class="name-mark" href="nouveautes-videoprojecteurs-Sony.php" title="Sony">Sony</a>
                </li>
                
                <li class="spacer"></li>
            </ul> -->
        </div>
        <!-- Fin accordeon -->
    </div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
        <div class="selecteur">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
        <div class="partenaire">
            <h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
            <form>
                <a href="partenariat.php"><div  class="btn-partenaire" onclick="location.href=annuaire-audiovisuel"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
            <h3>Nos trois boutiques</h3>
            <div class="list_carousel">
                <ul id="foo0">
                    <li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt=""  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt=""  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour même si la commande se fait avant 16h.</p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt=""  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->

