<?php  
$this->layout()->title = 'Devenir partenaire';
$this->headMeta()
                ->appendName('keywords', "Partenariat lampe vidéoprojecteur")
                ->appendName('description', "Devenez partenaire de lampe-videoprojecteur.info");
?>
<!-- Slider -->
<div class="box-line bg_slider">
    <div class="banniere_slide">
        <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
              <div class="carousel-inner">
                <!--Slide 1 -->
                
                <div class="item active">
                    <a href="annuaire-audiovisuel" >
                        <img src="images/slider/slide1.jpg" alt="Annuaire Audiovisuel" title="Annuaire Audiovisuel" />
                    </a>
                </div>
                
                <!--Slide 2 -->
                <div class="item">
                    <a href="http://www.focuslight.fr" target="_blank">
                        <img src="images/slider/slide2.jpg" alt="Focuslight" title="Focuslight" />
                    </a>
                </div>
                <!--Slide 3 -->
                <div class="item">
                    <a href="http://originalinsidelamps.com" target="_blank">
                        <img src="images/slider/slide3.jpg" alt="Originalinsidelamps" title="Originalinsidelamps" />
                    </a>
                </div>
                <!--Slide 4 -->
                <div class="item">
                      <a href="http://www.rienquedeslampes.fr" target="_blank">
                        <img src="images/slider/slide4.jpg" alt="rienquedeslampes" title="rienquedeslampes" />
                      </a>
                </div>
                <!--Slide 5 -->
                <div class="item">
                      <a href="http://www.affiche-cine.com" target="_blank">
                        <img src="images/slider/slide5.jpg" alt="affiche-cine" title="affiche-cinel" />
                      </a>
                </div>
              </div>
            <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="icon-prev"></span></a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="icon-next"></span></a>                  
        </div>
     </div>
</div>
<!-- End Slider -->

<div class="ariane">
    <p>
        <a href="home"><img src="images/ico-home.png" alt="" width="16" height="14" /></a>&nbsp;&gt;&nbsp;
        <span>Devenir Partenaire</span>
    </p>
</div>
<div class="containeur">
  <!-- Contenu -->
  <h1 class="titre_page">Devenir Partenaire</h1>
<div class="contenu">
   
<table width="680px" border="0" bgcolor="#ffffff" cellspacing="0" cellpadding="0">

<tr bgcolor=""><td colspan="2">&nbsp;</td><td align="center"><td>&nbsp;</td></td></tr>

<tr><td width="20"></td><td>&nbsp;</td><td align="center"></td><td></td></tr>

<tr><td colspan="2" width="200" align="center"><img src="images/partenaires-1.gif">
</td><td align="center" valign="top"><br><font size="+2"><font color="#4ABDD6"><span  style="color:#C0C0C0;"><b>Devenez partenaire de notre site d'information sur le vid&eacute;projecteur et sa lampe</font><br><font color="#FF7F00">et affichez votre site sur toutes nos pages</font></font><br><font size="-1" color="">(l'affichage se fait en ordre al&eacute;atoire)</font></td></tr><tr><td width="20"></td><td colspan="2">&nbsp;</td><td></td></tr>

<tr><td colspan="4" bgcolor="">&nbsp;</td></tr>

<tr><td width="20"></td><td colspan="2"></td><td></td></tr>
<tr><td colspan="2" width="200" align="center">
</td><td align="center"><font size="+2"><span  style="color:#C0C0C0;"><b><font color="#FF7F00">1</font><br><font color="#4ABDD6" size="+2">Installez un lien sur votre page d'accueil</font></font></b></span><br><br>
<font color="">Un simple lien texte, par exemple<br>
<textarea cols="60"><a href="http://www.lampe-videoprojecteur.info" target="_blank">Infos lampe videoprojecteur</a></textarea><br><br>
Si vous pr&eacute;f&eacute;rez une image, voyez en bas de cette page.</td></tr>
<tr><td width="20"></td><td colspan="2"></td><td></td></tr>

<tr><td colspan="4" bgcolor="">&nbsp;</td></tr>

<tr></td><td colspan="2"></td><td></td></tr>
<tr><td colspan="2" width="200" align="center"><img src="images/partenaires-3.gif">
</td><td align="center"><font size="+2"><span  style="color:#C0C0C0;"><b><font color="#FF7F00">2</font><br><font color="#4ABDD6">Contactez-nous</font></font></b></span><br><a href="contact.php"><font color="">en cliquant ici</font></a></td></tr>
<tr><td width="20"></td><td colspan="2"></td><td></td></tr>

<tr><td colspan="4" bgcolor="">&nbsp;</td></tr>

<tr><td width="20"></td><td colspan="2"></td><td></td></tr>
<tr><td colspan="2" width="200" align="center"><img src="images/partenaires-4.gif">
</td><td align="center"><font size="+2"><span  style="color:#C0C0C0;"><b><font color="#FF7F00">Attention</font><br><font color="#4ABDD6">Votre site web ou votre blog doit &ecirc;tre en rapport avec le home-cinema, le cin&eacute;ma ou la t&eacute;l&eacute;vision</font></td></tr>
<tr><td width="20"></td><td colspan="2"></td><td></td></tr>

<tr><td colspan="4" bgcolor="">&nbsp;</td></tr>

<tr><td></td><td colspan="2"></td><td></td></tr>

<tr><td colspan="2" width="200" align="center"><font color="404040">88x31 pixels</font></td>
<td align="center" colspan="2"><img src="images/88x31.gif"><br><br>
<textarea cols="60" rows="4"><a href="http://www.lampe-videoprojecteur.info" target="_blank"><img src="images/http://www.lampe-videoprojecteur.info/88x31.gif" alt="Info Lampe videoprojecteur"></a></textarea><br><br></td></tr>


<tr><td width="200" align="center"><font color="404040">90x60 pixels</font>
</td><td align="center" colspan="2"><img src="images/90x60.gif"><br><br>
<textarea cols="60" rows="4"><a href="http://www.lampe-videoprojecteur.info" target="_blank"><img src="images/http://www.lampe-videoprojecteur.info/90x60.gif" alt="Info Lampe videoprojecteur"></a></textarea><br><br></td></tr>

<tr><td width="200" align="center"><font color="404040">468x60 pixels</font>
</td><td align="center" colspan="2"><img src="images/468x60.gif"><br><br>
<textarea cols="60" rows="4"><a href="http://www.lampe-videoprojecteur.info" target="_blank"><img src="images/http://www.lampe-videoprojecteur.info/468x60.gif" alt="Info Lampe videoprojecteur"></a></textarea><br><br></td></tr>

<tr><td></td><td colspan="2"></td><td></td></tr>


</td></tr>
</table>        
      
</div>
    <!-- End Contenu -->
    <!-- Bloc left -->
    <div class="bloc_right">
        <div class="selecteur" style="margin-top:0px;">
            <h3>RECHERCHEZ VOTRE VIDEOPROJECTEUR</h3>
            <form>
                <select id="marque" name="marque">
                    <option value="">--Marque de vid&eacute;oprojecteur--</option>
                </select>
                <select id="model" name="model">
                    <option value="">--Mod&egrave;le de vid&eacute;oprojecteur--</option>
                </select>
                <p style="margin-top:15px;">
                <div onclick="href_info_produit();"  class="info-video" title="LampeVideoProjecteur info">Infos sur le vid&eacute;oprojecteur</div>

                <div class="prix-lampe" onclick="href_fiche_produit();" class="prix-lampe" title="LampeVideoProjecteur comprarer les prix">Prix de la lampe</div>
                </p>
            </form>
        </div>
        <div class="partenaire">
            <h3>Partenariat</h3>
            <p>Devenez partenaire de notre site d&acute;information sur le vid&eacute;projecteur et sa lampe et affichez votre site sur toutes nos pages</p>
            <form>
                <a href="partenariat.php"><div  class="btn-partenaire" onclick="location.href=annuaire-audiovisuel"/>Devenir partenaire</div></a>
            </form>
        </div>
        <div class="boutique">
            <h3>Nos trois boutiques</h3>
            <div class="list_carousel">
                <ul id="foo0">
                    <li>
                        <p><img src="images/logo-partenaire/boutik1.jpg" alt=""  />
                        Distributeur europ&eacute;en de lampes de vid&eacute;oprojecteur : originales, Original Inside et Genius. Une moyenne de 4.6/5 avec le service d'avis clients Ekomi (Calcul&eacute; &agrave; partir de 816 avis). Possibilit&eacute; de retrait sur place. </p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik2.png" alt=""  />
                        Sp&eacute;cialiste dans la vente de lampes Originales pour vid&eacute;oprojecteur. Lampe exp&eacute;di&eacute;e le jour même si la commande se fait avant 16h.</p>
                    </li>
                    <li>
                        <p><img src="images/logo-partenaire/boutik3.jpg" alt=""  />
                        Site de vente de lampes Original Inside. Service fiable et paiement en ligne s&eacute;curis&eacute;. 176 avis clients positifs. Toutes les lampes sont garanties 5 mois. </p>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- End left -->
    <div class="spacer"></div>
</div>
<!-- End Conteneur -->



