<?php if ($videoprojecteur == "3M") { header("Location: http://solutions.3mfrance.fr/wps/portal/3M/fr_FR/EU-Office/Home/ProdInfo/MeetingsPresentations/"); exit; } ?>
<?php if ($videoprojecteur == "ACER") { header("Location: http://www.acer.fr"); exit; } ?>
<?php if ($videoprojecteur == "Anders Kern") { header("Location: http://www.anders-kern.co.uk/"); exit; } ?>
<?php if ($videoprojecteur == "Barco") { header("Location: http://www.barco.com/"); exit; } ?>
<?php if ($videoprojecteur == "BenQ") { header("Location: http://benq.fr/products/Projector/"); exit; } ?>
<?php if ($videoprojecteur == "Canon") { header("Location: http://www.canon.fr/For_Home/Product_Finder/Multimedia_Projectors/index.asp"); exit; } ?>
<?php if ($videoprojecteur == "Casio") { header("Location: http://www.casio-europe.com/fr/dp/"); exit; } ?>
<?php if ($videoprojecteur == "Christie") { header("Location: http://www.christiedigital.com/"); exit; } ?>
<?php if ($videoprojecteur == "Compaq") { header("Location: http://www.compaq.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Dell") { header("Location: http://www.dell.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Dream vision") { header("Location: http://www.dreamvision.net/"); exit; } ?>
<?php if ($videoprojecteur == "Eiki") { header("Location: http://www.eiki.com/"); exit; } ?>
<?php if ($videoprojecteur == "Electrohome") { header("Location: http://electrohome.ca/electrohome/fr/home/"); exit; } ?>
<?php if ($videoprojecteur == "Epson") { header("Location: http://www.epson.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Fujitsu") { header("Location: http://fr.fujitsu.com/"); exit; } ?>
<?php if ($videoprojecteur == "Fujitsu-Siemens") { header("Location: http://fr.fujitsu.com/"); exit; } ?>
<?php if ($videoprojecteur == "Geha") { header("Location: http://www.geha.de/"); exit; } ?>
<?php if ($videoprojecteur == "Hewlett Packard") { header("Location: http://welcome.hp.com/country/fr/fr/welcome.html"); exit; } ?>
<?php if ($videoprojecteur == "Hitachi") { header("Location: http://www.hitachi.fr/"); exit; } ?>
<?php if ($videoprojecteur == "IBM") { header("Location: http://www.ibm.com/fr/fr/"); exit; } ?>
<?php if ($videoprojecteur == "Infocus") { header("Location: http://www.projecteursinfocus.fr/"); exit; } ?>
<?php if ($videoprojecteur == "LG") { header("Location: http://fr.lge.com/"); exit; } ?>
<?php if ($videoprojecteur == "Marantz") { header("Location: http://marantz.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Mitsubishi") { header("Location: http://www.mitsubishielectric.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Nec") { header("Location: http://www.nec.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Optoma") { header("Location: http://www.optoma.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Panasonic") { header("Location: http://www.panasonic.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Philips") { header("Location: http://www.philips.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Plus") { header("Location: http://www.plus-europe.com/"); exit; } ?>
<?php if ($videoprojecteur == "Projectiondesign") { header("Location: http://www.projectiondesign.com/"); exit; } ?>
<?php if ($videoprojecteur == "Proxima") { header("Location: http://www.askproxima.com/"); exit; } ?>
<?php if ($videoprojecteur == "Sagem") { header("Location: http://www.sagem-online.com/"); exit; } ?>
<?php if ($videoprojecteur == "Samsung") { header("Location: http://www.samsung.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Sanyo") { header("Location: http://www.sanyo.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Sharp") { header("Location: http://www.sharp.fr/"); exit; } ?>
<?php if ($videoprojecteur == "Sim2") { header("Location: http://www.sim2.com/"); exit; } ?>
<?php if ($videoprojecteur == "Sony") { header("Location: http://www.sony.fr"); exit; } ?>
<?php if ($videoprojecteur == "Thomson") { header("Location: http://fr.thomson.net/fr/home/"); exit; } ?>
<?php if ($videoprojecteur == "Toshiba") { header("Location: http://www.toshiba.fr"); exit; } ?>
<?php if ($videoprojecteur == "Viewsonic") { header("Location: http://www.viewsoniceurope.com/fr/"); exit; } ?>
<?php if ($videoprojecteur == "Yamaha") { header("Location: http://fr.yamaha.com/"); exit; } ?>




Le lien vers les projecteurs <b><?php echo $videoprojecteur ?></b> n'est pas encore en place sur le site...

</b></font>

<a href="http://www.xiti.com/xiti.asp?s=481598" title="WebAnalytics" target="_top">
<script type="text/javascript">
<!--
Xt_param = 's=481598&p=';
try {Xt_r = top.document.referrer;}
catch(e) {Xt_r = document.referrer; }
Xt_h = new Date();
Xt_i = '<img width="80" height="15" border="0" alt="" ';
Xt_i += 'src="http://logv1.xiti.com/g.xiti?'+Xt_param;
Xt_i += '&hl='+Xt_h.getHours()+'x'+Xt_h.getMinutes()+'x'+Xt_h.getSeconds();
if(parseFloat(navigator.appVersion)>=4)
{Xt_s=screen;Xt_i+='&r='+Xt_s.width+'x'+Xt_s.height+'x'+Xt_s.pixelDepth+'x'+Xt_s.colorDepth;}
document.write(Xt_i+'&ref='+Xt_r.replace(/[<>"]/g, '').replace(/&/g, '$')+'" title="Internet Audience">');
//-->
</script>
<noscript>
Mesure d'audience ROI statistique webanalytics par <img width="80" height="15" src="http://logv1.xiti.com/g.xiti?s=481598&p=" alt="WebAnalytics" />
</noscript></a>


