
        <div class="selecteur-pdf">
        	<h3 class="attr0">CHOISISSEZ VOTRE MODÈL PUIS INSÉREZ VOTRE FICHE PDF</h3>
            <div class="attr1">
            <form method="post" action="uploadpdf.html" enctype="multipart/form-data">
                <select id="marque-pdf" name="ref_model" class="attr2">
                <?php foreach ($marques as $key => $value):
                	if (!file_exists('public/manuels/manuels/'.ucfirst(strtolower($value["Manufacturer"])).'-'.strtoupper($value["ModelNo"]).'.pdf'))
    				{
                ?>
					<option required><?php echo ucfirst(strtolower($value["Manufacturer"])).'-'.strtoupper($value["ModelNo"]);?></option>
				<?php } endforeach; ?>
                   
                </select>
                <input type="file" class="attr3" name="uploadpdf" required>
                <input type="submit" name="setpdf" class="attr4" value="Enregistrer"><h3 class="msg_confirm"><?php  echo $success; ?></h3>
                </form>
                
            </div>
        </div>
