<style type="text/css">
    /*.bg_header, .marque, .footer{display: none;}*/
</style>

        <div class="selecteur-pdf">
        	<h3 class="attr0">CHOISISSEZ VOTRE MODÈL PUIS INSÉREZ VOTRE FICHE PDF</h3>
            <div class="attr1">
            <form method="post" action="uploadpdf.html" enctype="multipart/form-data">
                <select id="marque" name="ref_model" class="attr2">
                <?php foreach ($marques as $key => $value):
                	if (!file_exists('public/manuels/manuels/'.$value["Manufacturer"].'-'.$value["ModelNo"].'.pdf'))
    				{
                ?>
					<option required><?php echo $value["Manufacturer"].'-'.$value["ModelNo"];?></option>
				<?php } endforeach; ?>
                   
                </select>
                <input type="file" class="attr3" name="uploadpdf" required>
                <input type="submit" name="setpdf" class="attr4" value="Enregistrer">
                </form>
            </div>
        </div>
